httpserver:
  ip: "0.0.0.0"
  port: 8080
tcs:
  log:
    path: "./logs"
    fmt: "[%level] %datetime %fbase:%line] %msg" #log format
    size: "10485760" # 10MB
  auto_init:
    enable: false
    xml_path: "map.xml"
  visualization:
    resolution: 50
