#windows下注意该文件编码格式要为GBK格式,否则可以读取失败
log:
  path: "logs"
  # fmt: "[%levshort] %datetime{%y%M%d %H:%m:%s.%g} %logger %thread %fbase:%line] %msg" #log format
  fmt: "[%levshort %datetime{%y%M%d %H:%m:%s.%g} %fbase:%line] %msg" #log format
  size: "2097152" # 2MB
  # size: "1000" #
  max_num: 5 # 最大文件个数
  enable: true
  to_file: true
  to_stdout: true
httpserver:
  ip: "0.0.0.0" # 默认所有ip都可连接
  port: 8080
tcs:
  auto_init:
    enable: false # 启动时是否自动加载一个地图
    xml_path: "config/map.xml" #绝对目录或相对执行文件目录
